spring:
  datasource:
    driverClassName: org.h2.Driver
    password: root
    username: root
    url: jdbc:h2:mem:fornecedor
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
